openapi:
  service:
    title: CHECKIN-SERVICE doc # title that you will want to display in the Swagger UI
    version: 1.0.0
    url: http://localhost:8084
springdoc:
  api-docs:
    path: /checkin/api/v3/api-docs
  swagger-ui:
    path: /checkin/api/swagger-ui.html
