openapi:
  service:
    title: SEARCH-SERVICE doc # title that you will want to display in the Swagger UI
    version: 1.0.0
    url: http://localhost:8082
springdoc:
  api-docs:
    path: /search/api/v3/api-docs  
  swagger-ui:
    path: /search/api/swagger-ui.html
